apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-test-deployment
  namespace: default
  labels:
    app: efs-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efs-test-app
  template:
    metadata:
      labels:
        app: efs-test-app
    spec:
      containers:
        - name: app
          image: amazonlinux:latest
          command: ["/bin/sh"]
          args: 
            - "-c"
            - |
              echo "Pod $(hostname) starting EFS test application..."
              echo "EFS mount point: /data"
              mkdir -p /data/$(hostname)
              while true; do 
                echo "$(date) - Pod $(hostname): EFS is working!" >> /data/$(hostname)/out.txt
                echo "$(date) - Pod $(hostname): Writing to EFS..." 
                ls -la /data/
                sleep 15
              done
          volumeMounts:
            - name: efs-storage
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim
      restartPolicy: Always